# Nom de l'application
spring.application.name=football-game

# Configuration H2 (Base de données en mémoire, s'efface à chaque redémarrage)
spring.datasource.url=jdbc:h2:mem:footballdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permet d'accéder à l'interface console de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Affiche les requêtes SQL dans la console (pratique pour débugger)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update